#!/bin/zsh
git clone https://github.com/gxcuizy/Python.git
git clone https://github.com/joe011/python.git
git clone https://github.com/gto76/python-cheatsheet.git
git clone https://github.com/faif/python-patterns.git
git clone https://github.com/michaelliao/awesome-python3-webapp.git
git clone https://github.com/michaelliao/learn-python3.git
git clone https://github.com/wistbean/learn_python3_spider.git
git clone https://github.com/injetlee/Python.git
git clone https://github.com/geekcomputers/Python.git
git clone https://github.com/AtsushiSakai/PythonRobotics.git
git clone https://github.com/jakevdp/PythonDataScienceHandbook.git
git clone https://github.com/docker-library/python.git
git clone https://github.com/jackfrued/Python-100-Days.git
git clone https://github.com/xxg1413/python.git
git clone https://github.com/vinta/awesome-python.git
git clone https://github.com/521xueweihan/python.git
git clone https://github.com/Zy143L/python.git
git clone https://github.com/Pierian-Data/Complete-Python-3-Bootcamp.git
git clone https://github.com/lining0806/PythonSpiderNotes.git
git clone https://github.com/Jack-Cherish/python-spider.git
git clone https://github.com/Yonv1943/Python.git
git clone https://github.com/walter201230/Python.git
git clone https://github.com/realpython/python-guide.git
git clone https://github.com/yidao620c/python3-cookbook.git
git clone https://github.com/Show-Me-the-Code/python.git
git clone https://github.com/exercism/python.git
git clone https://github.com/taizilongxu/interview_python.git
git clone https://github.com/zhanghe06/python.git
git clone https://github.com/TheAlgorithms/Python.git
git clone https://github.com/poise/python.git
git clone https://github.com/joeyajames/Python.git
git clone https://github.com/Tanu-N-Prabhu/Python.git
git clone https://github.com/kubernetes-client/python.git
git clone https://github.com/dsacademybr/PythonFundamentos.git